name: FakeChat
options:
  bundleIdPrefix: com.ggsheng
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    DEVELOPMENT_TEAM: "9L6N2ZF26B"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "Apple Distribution: ZhiFeng Sun (9L6N2ZF26B)"
    CODE_SIGNING_REQUIRED: "YES"
    INFOPLIST_FILE: Sources/App/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.ggsheng.FakeChat
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    GENERATE_INFOPLIST_FILE: NO

targets:
  FakeChat:
    type: application
    platform: iOS
    sources:
      - Sources
      - Resources
    settings:
      base:
        INFOPLIST_FILE: Sources/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ggsheng.FakeChat
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: Sources/App/FakeChat.entitlements
      properties:
        com.apple.security.app-sandbox: true

  FakeChatUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - FakeChatUITests
    dependencies:
      - target: FakeChat
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ggsheng.FakeChat.UITests
        TEST_TARGET_NAME: FakeChat

schemes:
  FakeChat:
    build:
      targets:
        FakeChat: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FakeChatUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release